name: core-proxy
version: 0.0.0
author: RandomBungee
api-version: '1.20'

main: de.jokileda.core.proxy.Core

commands:
  punish:
  changerank:
  chatclear:
  help:
  kick:
  ping:
  pray:
  l:
  bauserver:
  unban: